stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "$DOCKERHUB_USERNAME/$CI_PROJECT_NAME"
  GOOGLE_APPLICATION_CREDENTIALS: "$CI_PROJECT_DIR/adc.json"
  TF_IN_AUTOMATION: "true"
  PROJECT_ID: "<your-gcp-project-id>"
  REGION: "us-central1"

before_script:
  - echo "$GOOGLE_USER_CREDENTIALS" | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
  - apt-get update && apt-get install -y jq
  - export REFRESH_TOKEN=$(cat $GOOGLE_APPLICATION_CREDENTIALS | jq -r .refresh_token)
  - export CLIENT_ID=$(cat $GOOGLE_APPLICATION_CREDENTIALS | jq -r .client_id)
  - export CLIENT_SECRET=$(cat $GOOGLE_APPLICATION_CREDENTIALS | jq -r .client_secret)
  - gcloud auth activate-refresh-token "$(gcloud config get-value account)" "$REFRESH_TOKEN"
  - gcloud config set project $PROJECT_ID
  - gcloud config set run/region $REGION

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve -var "docker_image=$DOCKER_IMAGE"
